import { useState } from 'react'
import { GitCommit, ExternalLink } from 'lucide-react'
import type { Entry, EntryType, CreateEntryRequest, GitHubSourceMeta } from '../../types'
import { ENTRY_TYPE_META } from '../../types'
import { Button } from '../ui/Button'
import { Input, Textarea, Select } from '../ui/Input'
import { TagBadge } from '../ui/TagBadge'
import { entriesApi } from '../../api/entries'
import { useEntryStore } from '../../store/entryStore'
import { toDateKey } from '../../utils/dateUtils'

interface EntryFormProps {
  date: Date
  entry?: Entry | null
  onClose: () => void
}

// Exclude COMMIT and GOAL from manual creation:
// - COMMIT is auto-generated by GitHub integration
// - GOAL is auto-generated by goal/milestone completion tracking
const MANUAL_TYPES = Object.entries(ENTRY_TYPE_META).filter(
  ([type]) => type !== 'COMMIT' && type !== 'GOAL'
) as [EntryType, typeof ENTRY_TYPE_META[EntryType]][]

const MOOD_OPTIONS = [
  { value: '', label: 'No mood' },
  { value: '1', label: '😞 Rough' },
  { value: '2', label: '😕 Meh' },
  { value: '3', label: '😐 Okay' },
  { value: '4', label: '🙂 Good' },
  { value: '5', label: '😄 Great' },
]

function parseSourceMeta(raw: string | null): GitHubSourceMeta | null {
  if (!raw) return null
  try { return JSON.parse(raw) } catch { return null }
}

// Read-only commit list shown inside the edit form for COMMIT entries
function CommitListReadOnly({ sourceMeta }: { sourceMeta: GitHubSourceMeta }) {
  return (
    <div className="rounded-lg overflow-hidden border border-border/60">
      <div className="flex items-center gap-2 px-3 py-1.5 bg-surface text-xs font-mono text-muted border-b border-border/60">
        <GitCommit size={11} />
        <span>{sourceMeta.repoFullName}</span>
        <span className="ml-auto text-[10px] bg-border/60 px-1.5 py-0.5 rounded">{sourceMeta.branch}</span>
      </div>
      <div className="divide-y divide-border/40 max-h-48 overflow-y-auto">
        {sourceMeta.commits.map(commit => (
          <div key={commit.sha} className="flex items-start gap-2 px-3 py-2">
            <span className="text-[10px] font-mono text-muted mt-0.5 shrink-0">{commit.sha.substring(0, 7)}</span>
            <p className="text-xs text-text/80 flex-1 leading-relaxed">{commit.message.split('\n')[0]}</p>
            <a
              href={commit.url}
              target="_blank"
              rel="noopener noreferrer"
              className="text-muted hover:text-accent shrink-0 mt-0.5 transition-colors"
            >
              <ExternalLink size={10} />
            </a>
          </div>
        ))}
      </div>
    </div>
  )
}

export function EntryForm({ date, entry, onClose }: EntryFormProps) {
  const { addEntry, updateEntry } = useEntryStore()
  const isEditing = !!entry
  const isCommit = entry?.entryType === 'COMMIT'
  const isGoalEntry = entry?.entryType === 'GOAL'
  const sourceMeta = parseSourceMeta(entry?.sourceMeta ?? null)

  const [title, setTitle]         = useState(entry?.title || '')
  const [content, setContent]     = useState(entry?.content || '')
  const [entryType, setEntryType] = useState<EntryType>(isCommit ? 'COMMIT' : (entry?.entryType || 'NOTE'))
  const [mood, setMood]           = useState(entry?.mood?.toString() || '')
  const [startTime, setStartTime] = useState(entry?.startTime || '')
  const [endTime, setEndTime]     = useState(entry?.endTime || '')
  const [tagInput, setTagInput]   = useState('')
  const [tags, setTags]           = useState<string[]>(entry?.tags.map(t => t.name) || [])
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError]         = useState('')

  const addTag = () => {
    const t = tagInput.trim().toLowerCase()
    if (t && !tags.includes(t)) setTags([...tags, t])
    setTagInput('')
  }

  const handleTagKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') { e.preventDefault(); addTag() }
    if (e.key === 'Backspace' && !tagInput && tags.length > 0) setTags(tags.slice(0, -1))
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!title.trim()) { setError('Title is required'); return }

    setIsLoading(true)
    setError('')

    try {
      if (isEditing && entry) {
        const updated = await entriesApi.update(entry.id, {
          title:      title.trim(),
          content:    content.trim() || undefined,
          entryDate:  toDateKey(date),
          mood:       mood ? parseInt(mood) : undefined,
          tags:       tags.length > 0 ? tags : undefined,
          startTime:  entryType === 'EVENT' && startTime ? startTime : undefined,
          endTime:    entryType === 'EVENT' && endTime   ? endTime   : undefined,
          isCompleted: entryType === 'ACTION' ? entry.isCompleted : undefined,
        })
        updateEntry(updated)
      } else {
        const payload: CreateEntryRequest = {
          title:      title.trim(),
          content:    content.trim() || undefined,
          entryType,
          entryDate:  toDateKey(date),
          mood:       mood ? parseInt(mood) : undefined,
          tags:       tags.length > 0 ? tags : undefined,
          startTime:  entryType === 'EVENT' && startTime ? startTime : undefined,
          endTime:    entryType === 'EVENT' && endTime   ? endTime   : undefined,
          isCompleted: entryType === 'ACTION' ? false : undefined,
        }
        const created = await entriesApi.create(payload)
        addEntry(created)
      }
      onClose()
    } catch (err: any) {
      setError(err.response?.data?.message || 'Something went wrong')
    } finally {
      setIsLoading(false)
    }
  }

  // ── GOAL entries: read-only — cannot be manually edited ───────────────────
  if (isGoalEntry) {
    return (
      <div className="flex flex-col gap-4 animate-fade-in">
        {/* Type badge */}
        <div className="flex items-center gap-2">
          <span
            className="text-xs font-mono px-2 py-1 rounded"
            style={{ color: ENTRY_TYPE_META.GOAL.color, backgroundColor: ENTRY_TYPE_META.GOAL.bg }}
          >
            🎯 Goal — auto-tracked
          </span>
        </div>

        {/* Entry details (read-only) */}
        <div className="rounded-lg border border-border/60 bg-surface p-4 flex flex-col gap-2">
          <p className="text-sm font-body font-medium text-primary">{entry?.title}</p>
          {entry?.content && (
            <p className="text-xs text-secondary">{entry.content}</p>
          )}
        </div>

        <p className="text-xs text-muted font-body leading-relaxed">
          This entry was automatically created when you completed a goal milestone and cannot be
          manually edited. To update this, change the completion status of the goal or milestone
          from the <strong className="text-secondary">Goals</strong> page.
        </p>

        <Button type="button" variant="ghost" onClick={onClose} className="w-full">
          Close
        </Button>
      </div>
    )
  }

  // ── COMMIT edit form — special layout ─────────────────────────────────────
  if (isCommit && isEditing) {
    return (
      <form onSubmit={handleSubmit} className="flex flex-col gap-4 animate-fade-in">
        {/* Type badge */}
        <div className="flex items-center gap-2">
          <span
            className="text-xs font-mono px-2 py-1 rounded"
            style={{ color: ENTRY_TYPE_META.COMMIT.color, backgroundColor: ENTRY_TYPE_META.COMMIT.bg }}
          >
            🔀 Commit — auto-generated
          </span>
        </div>

        {/* Commit list (read-only) */}
        {sourceMeta && (
          <div>
            <label className="text-xs font-mono text-muted uppercase tracking-widest block mb-1.5">
              Commits
            </label>
            <CommitListReadOnly sourceMeta={sourceMeta} />
          </div>
        )}

        {/* Title (editable) */}
        <Input
          label="Title"
          value={title}
          onChange={e => setTitle(e.target.value)}
          placeholder="Entry title..."
        />

        {/* Notes (editable — this is their reflection) */}
        <Textarea
          label="Your notes"
          value={content}
          onChange={e => setContent(e.target.value)}
          placeholder="What were you thinking? What did you learn from this work? Add your reflection here..."
          rows={4}
        />

        {/* Mood */}
        <Select
          label="Mood"
          value={mood}
          onChange={e => setMood(e.target.value)}
          options={MOOD_OPTIONS}
        />

        {/* Tags */}
        <div className="flex flex-col gap-1.5">
          <label className="text-xs font-body font-medium text-secondary uppercase tracking-widest">Tags</label>
          <div className="flex flex-wrap gap-1.5 p-2 bg-surface border border-border rounded-md min-h-[38px]">
            {tags.map(t => (
              <TagBadge key={t} tag={{ id: 0, name: t, color: '#38bdf8' }} onRemove={() => setTags(tags.filter(x => x !== t))} />
            ))}
            <input
              value={tagInput}
              onChange={e => setTagInput(e.target.value)}
              onKeyDown={handleTagKeyDown}
              onBlur={addTag}
              placeholder={tags.length === 0 ? 'Add tags...' : ''}
              className="flex-1 min-w-[80px] bg-transparent text-xs text-primary font-mono outline-none placeholder:text-muted"
            />
          </div>
        </div>

        {error && <p className="text-xs text-red-400">{error}</p>}

        <div className="flex gap-2 pt-1">
          <Button type="submit" loading={isLoading} className="flex-1">Save notes</Button>
          <Button type="button" variant="ghost" onClick={onClose}>Cancel</Button>
        </div>
      </form>
    )
  }

  // ── Standard entry form ───────────────────────────────────────────────────
  return (
    <form onSubmit={handleSubmit} className="flex flex-col gap-4 animate-fade-in">
      {/* Type selector (no COMMIT or GOAL for manual creation) */}
      <div className="flex gap-2">
        {MANUAL_TYPES.map(([type, meta]) => (
          <button
            key={type}
            type="button"
            onClick={() => setEntryType(type)}
            className={`flex-1 py-2 px-3 rounded-md text-xs font-mono border transition-all duration-150 ${
              entryType === type
                ? 'border-transparent text-bg font-medium'
                : 'border-border text-secondary hover:border-accent/30'
            }`}
            style={entryType === type ? { backgroundColor: meta.color } : {}}
          >
            {meta.icon} {meta.label}
          </button>
        ))}
      </div>

      <Input
        label="Title"
        value={title}
        onChange={e => setTitle(e.target.value)}
        placeholder={`What did you ${entryType === 'SKILL' ? 'learn' : entryType === 'ACTION' ? 'do' : 'note'}?`}
        autoFocus
      />

      <Textarea
        label="Details"
        value={content}
        onChange={e => setContent(e.target.value)}
        placeholder="Add more detail..."
        rows={4}
      />

      {entryType === 'EVENT' && (
        <div className="flex gap-3">
          <Input label="Start time" type="time" value={startTime} onChange={e => setStartTime(e.target.value)} className="flex-1" />
          <Input label="End time"   type="time" value={endTime}   onChange={e => setEndTime(e.target.value)}   className="flex-1" />
        </div>
      )}

      <Select label="Mood" value={mood} onChange={e => setMood(e.target.value)} options={MOOD_OPTIONS} />

      <div className="flex flex-col gap-1.5">
        <label className="text-xs font-body font-medium text-secondary uppercase tracking-widest">Tags</label>
        <div className="flex flex-wrap gap-1.5 p-2 bg-surface border border-border rounded-md min-h-[38px]">
          {tags.map(t => (
            <TagBadge key={t} tag={{ id: 0, name: t, color: '#818cf8' }} onRemove={() => setTags(tags.filter(x => x !== t))} />
          ))}
          <input
            value={tagInput}
            onChange={e => setTagInput(e.target.value)}
            onKeyDown={handleTagKeyDown}
            onBlur={addTag}
            placeholder={tags.length === 0 ? 'Add tags...' : ''}
            className="flex-1 min-w-[80px] bg-transparent text-xs text-primary font-mono outline-none placeholder:text-muted"
          />
        </div>
      </div>

      {error && <p className="text-xs text-red-400">{error}</p>}

      <div className="flex gap-2 pt-1">
        <Button type="submit" loading={isLoading} className="flex-1">
          {isEditing ? 'Save changes' : 'Add entry'}
        </Button>
        <Button type="button" variant="ghost" onClick={onClose}>Cancel</Button>
      </div>
    </form>
  )
}